"""add task status priority assignee

Revision ID: 0a79ea215b0f
Revises: 3e909a91d21f
Create Date: 2026-08-03 18:51:38.664240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0a79ea215b0f'
down_revision: Union[str, Sequence[str], None] = '3e909a91d21f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'DONE', name='taskstatus'), nullable=False))
    op.add_column('tasks', sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority'), nullable=False))
    op.add_column('tasks', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('tasks', 'created_by',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(
        "fk_tasks_assignee_id_users",
        "tasks",
        "users",
        ["assignee_id"],
        ["id"],
    )    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_tasks_assignee_id_users",
        "tasks",
        type_="foreignkey",
    )    
    op.alter_column('tasks', 'created_by',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    op.drop_column('tasks', 'assignee_id')
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###
