"""add role and created_by

Revision ID: 3e909a91d21f
Revises: cb5f490f930d
Create Date: 2026-08-03 16:48:34.065756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e909a91d21f'
down_revision: Union[str, Sequence[str], None] = 'cb5f490f930d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['created_by'], ['id'])
    op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'MEMBER', name='userrole'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'created_by')
    # ### end Alembic commands ###
