"""add project and due date to tasks

Revision ID: 98b3d078828a
Revises: cfb627db3424
Create Date: 2026-08-04 18:21:31.691746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '98b3d078828a'
down_revision: Union[str, Sequence[str], None] = 'cfb627db3424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('tasks', 'status',
               existing_type=mysql.ENUM('TODO', 'IN_PROGRESS', 'DONE'),
               type_=sa.Enum('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', name='taskstatus'),
               existing_nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=mysql.ENUM('LOW', 'MEDIUM', 'HIGH'),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority'),
               existing_nullable=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.alter_column('tasks', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority'),
               type_=mysql.ENUM('LOW', 'MEDIUM', 'HIGH'),
               existing_nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', name='taskstatus'),
               type_=mysql.ENUM('TODO', 'IN_PROGRESS', 'DONE'),
               existing_nullable=False)
    op.drop_column('tasks', 'due_date')
    op.drop_column('tasks', 'project_id')
    # ### end Alembic commands ###
