"""make task project required

Revision ID: b496fc92b632
Revises: 98b3d078828a
Create Date: 2026-08-04 18:26:10.894284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b496fc92b632'
down_revision: Union[str, Sequence[str], None] = '98b3d078828a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'project_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'project_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
